### ISSUE TITLE
IE and Edge support

### ISSUE THREAD

**Issue by awest1339** [clenk/multiscanner#12]
* Current implementation seems to only work in Chrome and FireFox.

**Comment by clenk** [comment]
It works in IE 10+. If you go to it in Edge and click “Keep going in Microsoft Edge” it will open the page correctly. In Internet Explorer you can change the document mode to IE 10 or 11 in the developer tools.

If you have intranet compatibility view turned on, another solution is to turn this off. Go to Tools -> Compatibility View settings and unchecking the “Display intranet sites in Compatibility View” box.

I'm closing this, but feel free to re-open it if we need to support versions of IE lower than 10.
