### ISSUE TITLE
Allow user to drag and drop a directory into scan box

### ISSUE THREAD

**Issue by awest1339** [clenk/multiscanner#17]
* Should be able to explode and grab all the sub files out of a given directory

**Comment by clenk** [comment]
We're using a jQuery plugin for file uploading, and it only supports directory upload with the file picker button, not drag-and-drop. Also, this functionality is only supported in Edge, Firefox, Chrome, and Opera.

We could add an "Select Folder(s)..." button next to "Select File(s)..." but I'm not sure this is something we should add right now.

See:
- [Bootstrap File Input: Folder Upload Demo](http://plugins.krajee.com/file-folder-upload-demo)
- [Can I Use... Directory selection from file input](http://caniuse.com/#feat=input-file-directory)

**Comment by awest1339** [comment]
Users are encouraged to zip the directory and submit it via the web UI. Otherwise, they may use the REST API for bulk submissions
