### ISSUE TITLE
Use a web.ini in MS_WD to configure the web application

### ISSUE THREAD

**Issue by awest1339** [clenk/multiscanner#18]
* Open to suggestions, but I think its better to have one standard way of configuring things w/i multiscanner

**Comment by clenk** [comment]
@awest1339 Which options do you have in mind to include in a web.ini?

**Comment by awest1339** [comment]
Everything that is in config.py currently I think

**Comment by awest1339** [comment]
Fixed by 61d9f409e37134895fa86f0483f889f4c41c400a
