### ISSUE TITLE
Give user option to Expand All subfields

### ISSUE THREAD

**Issue by awest1339** [clenk/multiscanner#26]
* Example for the Yara module, which contains many subfields:
Yara               Expand(+)                 Expand All (+)

**Comment by clenk** [comment]
What if Shift-clicking the Expand button expanded all subfields, to avoid cluttering interface with another button? This would be documented of course.

**Comment by awest1339** [comment]
This sounds reasonable. Would it be possible to have that in a text box pop up if a user hovers the mouse over it?

**Comment by clenk** [comment]
Yes; it can be like the popups on the Notes and Download JSON buttons.

**Comment by clenk** [comment]
Addressed by d59902e.

Feel free to reopen if this is insufficient.
