### ISSUE TITLE
Enable user to set resubmissions of same file to pull latest report or perform a new scan

### ISSUE THREAD

**Issue by clenk** [clenk/multiscanner#36]
What should the default be?

**Comment by awest1339** [comment]
Let's set the default to be pull the latest report, unless the config passed in is different

**Comment by clenk** [comment]
Recently pushed a commit that defaults to pulling the latest report. Checking the config that was passed in will be more tricky, as it will have to check the report (making a query to Elasticsearch as well instead of just to the task db). Do we want to add this complexity? Will users be confused if they tell it to rescan but it doesn't because the config hasn't changed?

I'm inclined to leave it up to the user to know when they've changed their config and want to resubmit. See also https://github.com/clenk/multiscanner/issues/31

**Comment by awest1339** [comment]
Yeah that makes sense. Default to returning the latest report, then do a rescan if the user requests it and don't bother with checking config changes or anything.

**Comment by clenk** [comment]
Fixed in 4173b35
